server:
  port: 9002
eureka:
  client:
    registerWithEureka: false #不注册到Eureka,不在注册中心显示
    service-url:
      defaultZone: http://localhost:7001/eureka
feign:
   hystrix:
       enabled: true #开启熔断支持
   client:
    config:
      remote-service:           #服务名，填写default为所有服务
        connectTimeout: 3000    #设置feign的响应超时时间，超过多少秒进行熔断降级处理
        readTimeout: 3000
hystrix:
  command:
      default:
        execution:
          isolation:
            thread:
              timeoutInMilliseconds: 3000  #设置hystrix的响应超时时间，feign和hystrix都需要设置